global using System;
global using System.Threading;
global using System.Threading.Tasks;
global using MediatR;
global using FluentValidation;
global using Microsoft.Extensions.Logging;
global using Microsoft.EntityFrameworkCore;
global using BuildingBlocks.Core.Functional.Results;
global using BuildingBlocks.Core.Diagnostics.Errors;
global using BuildingBlocks.Core.Abstractions.CQRS;
global using Axon.Modules.Chat.Domain.ValueObjects;
global ;
global using BuildingBlocks.Core.Abstractions.Authentication;
global using Axon.Modules.Chat.Application.Abstractions.Persistence;