// <auto-generated />
using System;
using Axon.Modules.Identity.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Axon.Modules.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityWriteDbContext))]
    [Migration("20250913172156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("RiskTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_tier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_principal");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_principal_created_at");

                    b.HasIndex("RiskTier")
                        .HasDatabaseName("ix_principal_risk_tier");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_principal_type");

                    b.ToTable("principal", "identity");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Aggregates.Wallet.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("ChainId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chain_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_wallet");

                    b.HasIndex("ChainId")
                        .HasDatabaseName("ix_wallet_chain_id");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_wallet_last_seen_at");

                    b.HasIndex("ChainId", "Address")
                        .IsUnique()
                        .HasDatabaseName("ux_wallet_chain_address");

                    b.ToTable("wallet", "identity");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Entities.IdentityCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("issuer");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_credential");

                    b.HasIndex("PrincipalId")
                        .HasDatabaseName("ix_credential_principal_id");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_credential_provider");

                    b.HasIndex("Provider", "Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_credential_provider_issuer_subject");

                    b.ToTable("credential", "identity");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Entities.PrincipalChainDefault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChainId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chain_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_principal_chain_default");

                    b.HasIndex("PrincipalId")
                        .HasDatabaseName("ix_default_principal_id");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_default_wallet_id");

                    b.HasIndex("PrincipalId", "ChainId")
                        .IsUnique()
                        .HasDatabaseName("ix_principal_chain_default_unique");

                    b.ToTable("principal_chain_default", "identity");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Entities.WalletOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("access_mode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_ownership");

                    b.HasIndex("PrincipalId")
                        .HasDatabaseName("ix_ownership_principal_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ownership_status");

                    b.HasIndex("WalletId")
                        .IsUnique()
                        .HasDatabaseName("ix_ownership_wallet_id")
                        .HasFilter("status = 'Verified' AND access_mode = 'Signing'");

                    b.HasIndex("PrincipalId", "WalletId")
                        .IsUnique()
                        .HasDatabaseName("ux_ownership_principal_wallet");

                    b.ToTable("wallet_ownership", "identity");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Entities.IdentityCredential", b =>
                {
                    b.HasOne("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", null)
                        .WithMany("Credentials")
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credential_principal_principal_id");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Entities.WalletOwnership", b =>
                {
                    b.HasOne("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", null)
                        .WithMany("WalletOwnerships")
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_ownership_principal_principal_id");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("WalletOwnerships");
                });
#pragma warning restore 612, 618
        }
    }
}
