// <auto-generated />
using System;
using Axon.Modules.Identity.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Axon.Modules.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityWriteDbContext))]
    partial class IdentityWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RiskTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_principal_created_at");

                    b.HasIndex("RiskTier")
                        .HasDatabaseName("ix_principal_risk_tier");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_principal_type");

                    b.ToTable("Principal", "identity");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Aggregates.Wallet.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("ChainId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chain_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ChainId")
                        .HasDatabaseName("idx_wallet_chain_id");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("idx_wallet_last_seen_at");

                    b.HasIndex("ChainId", "Address")
                        .IsUnique()
                        .HasDatabaseName("ux_wallet_chain_addr")
                        .HasFilter("is_deleted = false");

                    b.ToTable("Wallet", "identity");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "identity");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage", "identity");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "identity");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", b =>
                {
                    b.OwnsMany("Axon.Modules.Identity.Domain.Entities.IdentityCredential", "Credentials", b1 =>
                        {
                            b1.Property<Guid>("PrincipalId")
                                .HasColumnType("uuid")
                                .HasColumnName("principal_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("created_at");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("deleted_at");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<string>("Issuer")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("issuer");

                            b1.Property<DateTime>("LastSeenAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("last_seen_at");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("provider");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("subject");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("updated_at");

                            b1.HasKey("PrincipalId", "Id");

                            b1.HasIndex("Provider", "Issuer", "Subject")
                                .IsUnique()
                                .HasDatabaseName("ux_credential_provider")
                                .HasFilter("is_deleted = false");

                            b1.ToTable("Credential", "identity");

                            b1.WithOwner()
                                .HasForeignKey("PrincipalId");
                        });

                    b.OwnsMany("Axon.Modules.Identity.Domain.Entities.PrincipalChainDefault", "PrincipalChainDefaults", b1 =>
                        {
                            b1.Property<Guid>("PrincipalId")
                                .HasColumnType("uuid")
                                .HasColumnName("principal_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ChainId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("chain_id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("created_at");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("deleted_at");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("updated_at");

                            b1.Property<Guid>("WalletId")
                                .HasColumnType("uuid")
                                .HasColumnName("wallet_id");

                            b1.HasKey("PrincipalId", "Id");

                            b1.HasIndex("PrincipalId")
                                .HasDatabaseName("idx_default_principal_id");

                            b1.HasIndex("WalletId")
                                .HasDatabaseName("idx_default_wallet_id");

                            b1.HasIndex("PrincipalId", "ChainId")
                                .IsUnique()
                                .HasDatabaseName("ux_chain_default")
                                .HasFilter("is_deleted = false");

                            b1.ToTable("PrincipalChainDefault", "identity");

                            b1.WithOwner()
                                .HasForeignKey("PrincipalId");
                        });

                    b.OwnsMany("Axon.Modules.Identity.Domain.Entities.WalletOwnership", "WalletOwnerships", b1 =>
                        {
                            b1.Property<Guid>("PrincipalId")
                                .HasColumnType("uuid")
                                .HasColumnName("principal_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AccessMode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("access_mode");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("created_at");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("deleted_at");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<string>("RevokeReason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("revoke_reason");

                            b1.Property<DateTime?>("RevokedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("revoked_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("updated_at");

                            b1.Property<string>("VerificationSource")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("verification_source");

                            b1.Property<DateTime?>("VerifiedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("verified_at");

                            b1.Property<Guid>("WalletId")
                                .HasColumnType("uuid")
                                .HasColumnName("wallet_id");

                            b1.HasKey("PrincipalId", "Id");

                            b1.HasIndex("WalletId")
                                .HasDatabaseName("idx_ownership_wallet_id");

                            b1.HasIndex("PrincipalId", "WalletId")
                                .IsUnique()
                                .HasDatabaseName("ux_ownership_pair")
                                .HasFilter("is_deleted = false");

                            b1.HasIndex("WalletId", "AccessMode", "Status")
                                .IsUnique()
                                .HasDatabaseName("ux_exclusive_signing")
                                .HasFilter("access_mode = 'Signing' AND status = 'Verified' AND is_deleted = false");

                            b1.ToTable("WalletOwnership", "identity");

                            b1.WithOwner()
                                .HasForeignKey("PrincipalId");
                        });

                    b.Navigation("Credentials");

                    b.Navigation("PrincipalChainDefaults");

                    b.Navigation("WalletOwnerships");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
