// <auto-generated />
using System;
using Axon.Modules.Identity.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Axon.Modules.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PrimaryEmailHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("primary_email_hash");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_axon_principals");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_axon_principals_created_at");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_axon_principals_type");

                    b.ToTable("axon_principals", "identity");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Aggregates.Wallet.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chain");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("_tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasIndex("Address")
                        .HasDatabaseName("ix_wallets_address");

                    b.HasIndex("Chain")
                        .HasDatabaseName("ix_wallets_chain");

                    b.HasIndex("FirstSeenAt")
                        .HasDatabaseName("ix_wallets_first_seen_at");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_wallets_last_seen_at");

                    b.HasIndex("Chain", "Address")
                        .IsUnique()
                        .HasDatabaseName("ix_wallets_chain_address_unique");

                    b.ToTable("wallets", "identity");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Entities.IdentityCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AxonId")
                        .HasColumnType("uuid")
                        .HasColumnName("axon_id");

                    b.Property<Guid?>("AxonPrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("axon_principal_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EnvironmentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_type");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_identity_credentials");

                    b.HasIndex("AxonId")
                        .HasDatabaseName("ix_credentials_axon_id");

                    b.HasIndex("AxonPrincipalId")
                        .HasDatabaseName("ix_identity_credentials_axon_principal_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_credentials_created_at");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_credentials_last_seen_at");

                    b.HasIndex("ProviderType", "Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_credentials_provider_issuer_subject_unique");

                    b.ToTable("identity_credentials", "identity");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Entities.WalletOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("access_mode");

                    b.Property<Guid>("AxonId")
                        .HasColumnType("uuid")
                        .HasColumnName("axon_id");

                    b.Property<Guid?>("AxonPrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("axon_principal_id");

                    b.Property<string>("ChainId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chain_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("FirstLinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_linked_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<string>("ProofType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("proof_type");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_ownerships");

                    b.HasIndex("AxonId")
                        .HasDatabaseName("ix_wallet_ownerships_axon_id");

                    b.HasIndex("AxonPrincipalId")
                        .HasDatabaseName("ix_wallet_ownerships_axon_principal_id");

                    b.HasIndex("ChainId")
                        .HasDatabaseName("ix_wallet_ownerships_chain_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_wallet_ownerships_created_at");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_wallet_ownerships_wallet_id");

                    b.HasIndex("State", "AccessMode")
                        .HasDatabaseName("ix_wallet_ownerships_state_access_mode")
                        .HasFilter("is_deleted = false");

                    b.ToTable("wallet_ownerships", "identity");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", b =>
                {
                    b.OwnsOne("Axon.Modules.Identity.Domain.Entities.PrincipalProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("AxonPrincipalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("DefaultPerChain")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("default_per_chain");

                            b1.Property<string>("PreferredLanguage")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("preferred_language");

                            b1.Property<string>("RiskTier")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("risk_tier");

                            b1.HasKey("AxonPrincipalId")
                                .HasName("pk_axon_principals");

                            b1.ToTable("axon_principals", "identity");

                            b1.WithOwner()
                                .HasForeignKey("AxonPrincipalId")
                                .HasConstraintName("fk_axon_principals_axon_principals_id");
                        });

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Entities.IdentityCredential", b =>
                {
                    b.HasOne("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", null)
                        .WithMany()
                        .HasForeignKey("AxonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_credentials_axon_principals_axon_id");

                    b.HasOne("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", null)
                        .WithMany("Credentials")
                        .HasForeignKey("AxonPrincipalId")
                        .HasConstraintName("fk_identity_credentials_axon_principals_axon_principal_id");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Entities.WalletOwnership", b =>
                {
                    b.HasOne("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", null)
                        .WithMany()
                        .HasForeignKey("AxonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_ownerships_axon_principals_axon_id");

                    b.HasOne("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", null)
                        .WithMany("WalletOwnerships")
                        .HasForeignKey("AxonPrincipalId")
                        .HasConstraintName("fk_wallet_ownerships_axon_principals_axon_principal_id");
                });

            modelBuilder.Entity("Axon.Modules.Identity.Domain.Aggregates.AxonPrincipal.AxonPrincipal", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("WalletOwnerships");
                });
#pragma warning restore 612, 618
        }
    }
}
