// <auto-generated />
using System;
using Axon.Modules.Chat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Axon.Modules.Chat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20250804215145_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("chat")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gin");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_stat_statements");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axon.Modules.Chat.Domain.Aggregates.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("version");

                    b.Property<DateTime>("_createdAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("_createdBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("system")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("_updatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("_updatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("system")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ix_conversations_status")
                        .HasFilter("status IN ('Active', 'Completed')");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_ix_conversations_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("_createdAtUtc")
                        .HasDatabaseName("ix_ix_conversations_created_at_utc");

                    b.HasIndex("_updatedAtUtc")
                        .HasDatabaseName("ix_ix_conversations_updated_at_utc");

                    b.HasIndex("Status", "CompletedAt")
                        .HasDatabaseName("ix_ix_conversations_status_completed_at")
                        .HasFilter("completed_at IS NOT NULL");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_ix_conversations_user_id_status")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("UserId", "_createdAtUtc")
                        .HasDatabaseName("ix_ix_conversations_user_id_created_at");

                    b.HasIndex("_createdBy", "_createdAtUtc")
                        .HasDatabaseName("ix_ix_conversations_created_audit");

                    b.ToTable("conversations", "chat", t =>
                        {
                            t.HasCheckConstraint("ck_conversations_audit_valid", "created_at_utc IS NOT NULL AND updated_at_utc IS NOT NULL AND updated_at_utc >= created_at_utc");

                            t.HasCheckConstraint("ck_conversations_completed_at_logic", "(status = 'Active' AND completed_at IS NULL) OR (status IN ('Completed', 'Archived') AND completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_conversations_status_valid", "status IN ('Active', 'Completed', 'Archived')");

                            t.HasCheckConstraint("ck_conversations_title_valid", "title IS NOT NULL AND LENGTH(TRIM(title)) > 0 AND LENGTH(title) <= 500");
                        });
                });

            modelBuilder.Entity("Axon.Modules.Chat.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateTime>("_createdAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("_createdBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("system")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("_updatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("_updatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("system")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_ix_messages_conversation_id");

                    b.HasIndex("Metadata")
                        .HasDatabaseName("ix_ix_messages_metadata_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Metadata"), "gin");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_ix_messages_role")
                        .HasFilter("role IN ('user', 'assistant', 'system', 'tool')");

                    b.HasIndex("_createdAtUtc")
                        .HasDatabaseName("ix_ix_messages_created_at_utc");

                    b.HasIndex("_updatedAtUtc")
                        .HasDatabaseName("ix_ix_messages_updated_at_utc");

                    b.HasIndex("ConversationId", "Role")
                        .HasDatabaseName("ix_ix_messages_conversation_id_role");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_ix_messages_conversation_id_sequence");

                    b.HasIndex("ConversationId", "_createdAtUtc")
                        .HasDatabaseName("ix_ix_messages_conversation_id_created_at_utc");

                    b.HasIndex("_createdBy", "_createdAtUtc")
                        .HasDatabaseName("ix_ix_messages_created_audit");

                    b.ToTable("messages", "chat", t =>
                        {
                            t.HasCheckConstraint("ck_messages_audit_valid", "created_at_utc IS NOT NULL AND updated_at_utc IS NOT NULL AND updated_at_utc >= created_at_utc");

                            t.HasCheckConstraint("ck_messages_content_valid", "content IS NOT NULL AND LENGTH(TRIM(content)) > 0 AND LENGTH(content) <= 100000");

                            t.HasCheckConstraint("ck_messages_conversation_id_valid", "conversation_id IS NOT NULL");

                            t.HasCheckConstraint("ck_messages_role_valid", "role IN ('user', 'assistant', 'system', 'tool')");

                            t.HasCheckConstraint("ck_messages_sequence_valid", "sequence > 0");
                        });
                });

            modelBuilder.Entity("Axon.Modules.Chat.Infrastructure.Persistence.Entities.DeadLetterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FailureStackTrace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failure_stack_trace");

                    b.Property<bool>("IsReprocessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reprocessed");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("MovedToDeadLetterAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("moved_to_dead_letter_at_utc");

                    b.Property<Guid>("OriginalMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_message_id");

                    b.Property<DateTime>("OriginalOccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("processing_attempts");

                    b.Property<DateTime?>("ReprocessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reprocessed_at_utc");

                    b.HasKey("Id");

                    b.ToTable("dead_letter_messages", "chat");
                });

            modelBuilder.Entity("Axon.Modules.Chat.Infrastructure.Persistence.Entities.EventCorrelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine_name");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.HasKey("Id");

                    b.ToTable("event_correlations", "chat");
                });

            modelBuilder.Entity("Axon.Modules.Chat.Infrastructure.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("processing_attempts");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", "chat");
                });

            modelBuilder.Entity("Axon.Modules.Chat.Domain.Entities.Message", b =>
                {
                    b.HasOne("Axon.Modules.Chat.Domain.Aggregates.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fk_messages_conversations_conversation_id");
                });
#pragma warning restore 612, 618
        }
    }
}
