namespace BuildingBlocks.Core.Diagnostics.Errors;

/// <summary>
/// RFC 7807 Problem Details representation.
/// Framework-agnostic DTO for standardized error responses.
/// </summary>
public sealed class Problem
{
    /// <summary>
    /// A URI reference that identifies the problem type.
    /// </summary>
    public string? Type { get; init; }
    
    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    public string? Title { get; init; }
    
    /// <summary>
    /// The HTTP status code generated by the origin server.
    /// </summary>
    public int Status { get; init; }
    
    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string? Detail { get; init; }
    
    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// </summary>
    public string? Instance { get; init; }

    /// <summary>
    /// W3C trace id for correlation (maps to correlation id).
    /// </summary>
    public string? TraceId { get; init; }

    /// <summary>
    /// Additional problem-specific extension fields (code, severity, metadata, causes, etc.).
    /// </summary>
    public Dictionary<string, object> Extensions { get; } = new();
}