using Microsoft.IdentityModel.Tokens;
using Axon.Modules.Identity.Application.Contracts.ExternalServices;
using BuildingBlocks.Core.Diagnostics.Errors;
using CSharpFunctionalExtensions;

namespace Axon.Modules.Identity.E2E.Infrastructure;

/// <summary>
/// Test implementation of IJwksService that returns test RSA keys
/// instead of fetching from production Dynamic API.
/// This ensures DynamicAuthService uses the same keys as the JWT middleware for E2E tests.
/// </summary>
public sealed class TestJwksService : IJwksService
{
    /// <summary>
    /// Returns test RSA keys that match the tokens generated by JwtTestTokenFactory.
    /// </summary>
    public Task<Result<ICollection<SecurityKey>, Error>> GetJwksKeysAsync(
        CancellationToken cancellationToken = default)
    {
        // Return test RSA keys that match the tokens generated by JwtTestTokenFactory
        var testKeys = JwtTestTokenFactory.GetTestSigningKeys().ToList();
        ICollection<SecurityKey> keysCollection = testKeys;

        var result = Result.Success<ICollection<SecurityKey>, Error>(keysCollection);
        return Task.FromResult(result);
    }
}