<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>CA1062;CA1822;CA1869;NUnit1033</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="Shouldly" />
    
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Shared/Common/Axon.Shared.Common.csproj" />
    <ProjectReference Include="../../src/Shared/Common.Abstractions/Axon.Shared.Common.Abstractions.csproj" />
    <ProjectReference Include="../../src/Shared/Domain/Axon.Shared.Domain.csproj" />
    <ProjectReference Include="../Shared/Axon.Tests.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
    <Using Include="Shouldly" />
    <Using Include="Moq" />
    <Using Include="Axon.Tests.Shared" />
  </ItemGroup>

</Project>